"""
Read status sync — Palma override import.

Reads the palma_readstatus_overrides.csv generated by the CalibreFanFicBrowser
Android app and writes only the #readstatus values that have changed back to
Calibre.  Stories whose status already matches are silently skipped.
"""

import csv
from dataclasses import dataclass, field
from pathlib import Path

from orchestrator.sync import calibre


# ---------------------------------------------------------------------------
# CSV parsing
# ---------------------------------------------------------------------------

def parse_palma_csv(path: Path) -> dict[int, str]:
    """
    Parse a Palma read-status override CSV.

    Accepts either column naming convention:
      - ID column:     ``id``  or  ``calibre_id``
      - Status column: ``readstatus``  or  ``#readstatus``

    Returns ``{calibre_id: status}`` for every row with a non-empty status.
    Raises ``ValueError`` if required columns cannot be found.
    """
    with open(path, encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        headers = list(reader.fieldnames or [])

        id_col = _find_col(headers, ("id", "calibre_id"))
        status_col = _find_col(headers, ("readstatus", "#readstatus"))

        if id_col is None:
            raise ValueError(
                f"No ID column found in {path.name!r}. "
                "Expected 'id' or 'calibre_id'."
            )
        if status_col is None:
            raise ValueError(
                f"No status column found in {path.name!r}. "
                "Expected 'readstatus' or '#readstatus'."
            )

        result: dict[int, str] = {}
        for row in reader:
            try:
                cid = int(row[id_col])
                status = row[status_col].strip()
                if status:
                    result[cid] = status
            except (ValueError, KeyError):
                continue

    return result


def _find_col(headers: list[str], candidates: tuple[str, ...]) -> str | None:
    """Return the first candidate that appears in headers (case-insensitive)."""
    for candidate in candidates:
        if candidate in headers:
            return candidate
    lower_map = {h.lower(): h for h in headers}
    for candidate in candidates:
        if candidate.lower() in lower_map:
            return lower_map[candidate.lower()]
    return None


# ---------------------------------------------------------------------------
# Status normalisation
# ---------------------------------------------------------------------------

def _normalize_status(status: str) -> str:
    """
    Return the canonical capitalisation for a read-status value.

    "DNF" is all-caps; everything else is title-cased.
    Examples: "read" → "Read", "favorite" → "Favorite", "dnf" → "DNF".
    """
    if status.upper() == "DNF":
        return "DNF"
    return status.title()


# ---------------------------------------------------------------------------
# Diff + write
# ---------------------------------------------------------------------------

@dataclass
class ReadStatusSyncResult:
    updated: list[int] = field(default_factory=list)
    updated_titles: dict[int, str] = field(default_factory=dict)        # cid → title
    updated_ao3_work_ids: dict[int, str] = field(default_factory=dict)  # cid → ao3_work_id
    updated_statuses: dict[int, str] = field(default_factory=dict)      # cid → normalized status
    skipped: list[int] = field(default_factory=list)
    failed: list[tuple[int, str]] = field(default_factory=list)


def sync_readstatus_from_palma(path: Path) -> ReadStatusSyncResult:
    """
    Parse *path*, compare against current Calibre #readstatus values, and
    write only the entries that differ.

    Skips IDs not present in the library without raising an error.
    Returns a :class:`ReadStatusSyncResult` with updated/skipped/failed IDs.
    """
    overrides = parse_palma_csv(path)
    library = calibre.fetch_library()
    current: dict[int, str] = {
        int(book["id"]): (book.get("#readstatus") or "").strip()
        for book in library
    }
    book_meta: dict[int, dict] = {int(book["id"]): book for book in library}

    result = ReadStatusSyncResult()

    for cid, new_status in overrides.items():
        if cid not in current:
            # ID not in this Calibre library — skip silently.
            result.skipped.append(cid)
            continue

        # "unread" is the Palma default for any book not explicitly marked.
        # Syncing it back would overwrite "read"/"Favorite"/etc. with the
        # default, which is never the intent.  Skip it — only sync deliberate
        # non-default status changes.
        if new_status.lower() == "unread":
            result.skipped.append(cid)
            continue

        normalized = _normalize_status(new_status)
        if current[cid].lower() == normalized.lower():
            result.skipped.append(cid)
            continue

        try:
            calibre.set_custom(cid, "#readstatus", normalized)
            try:
                calibre.touch_last_modified(cid)
            except Exception:
                pass  # Non-critical — readstatus was written successfully
            result.updated.append(cid)
            b = book_meta.get(cid, {})
            result.updated_titles[cid] = (b.get("title") or "").strip()
            result.updated_ao3_work_ids[cid] = (b.get("#ao3_work_id") or "").strip()
            result.updated_statuses[cid] = normalized
        except Exception as exc:
            result.failed.append((cid, str(exc)))

    return result
